services:
    master:
        ports:
            # - 54310:54310   # HDFS Remote DFS port
            - 9870:9870     # Web UI
        networks:
            - sabd-net
        container_name: master
        image: matnar/hadoop
        depends_on:
            - slave1
            - slave2
            - slave3
        tty: true
        stdin_open: true
        volumes:
          - "${DATA_DIR}:/app/dataset"

    slave1:
        ports:
            - 9864:9864
        networks:
            - sabd-net
        container_name: slave1
        image: matnar/hadoop
        tty: true
        stdin_open: true
        
    slave2:
        ports:
            - 9863:9864
        networks:
            - sabd-net
        container_name: slave2
        image: matnar/hadoop
        tty: true
        stdin_open: true

    slave3:
        ports:
            - 9862:9864
        networks:
            - sabd-net
        container_name: slave3
        image: matnar/hadoop
        tty: true
        stdin_open: true

networks:
    sabd-net:
        name: sabd-net
        driver: bridge
        external: true
        